# Generated by Django 5.1.3 on 2024-12-17 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramBotConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(default='token', max_length=255)),
                ('secret_key', models.CharField(default='secret_key', max_length=255)),
                ('webhook_url', models.URLField(default='https://api.telegram.org/', max_length=255)),
                ('admin', models.IntegerField(default=1235678)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('phone_number', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('detections_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CarListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('url', models.URLField(unique=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mileage', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.carbrand')),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('car_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bot.carlisting')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='bot.carbrand')),
            ],
        ),
        migrations.AddField(
            model_name='carlisting',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.carmodel'),
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color')),
                ('year_from', models.PositiveIntegerField(blank=True, null=True)),
                ('year_to', models.PositiveIntegerField(blank=True, null=True)),
                ('mileage_from', models.PositiveIntegerField(blank=True, null=True)),
                ('mileage_to', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.carbrand', verbose_name='Car brand')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.carmodel', verbose_name='Model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection', to='bot.user')),
            ],
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_progress', 'Jarayonda'), ('completed', 'Bajarildi'), ('failed', 'Xato')], max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='bot.detection')),
            ],
        ),
    ]
