name: Deploy Django Bot

on:
  push:
    branches:
      - main

jobs:
  install_project:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install -r requirements/production.txt

    - name: Sync files
      run: |
        sudo rsync -av --delete-after --exclude=".git/" --exclude=".gitlab-ci.yml" --exclude="media/" --exclude="staticfiles/" --exclude="static/" --exclude=".env" --exclude="venv/" --exclude="local_settings.py" --exclude="dev.py" --exclude="prod.py" --exclude="__pycache__/" . /var/www/django-bot/

    - name: Run database migrations
      run: |
        . venv/bin/activate
        python manage.py migrate

    - name: Collect static files
      run: |
        . venv/bin/activate
        python manage.py collectstatic --no-input

    - name: Compile translations
      run: |
        . venv/bin/activate
        pybabel compile -d locale -D django

    - name: Restart services
      run: |
        sudo systemctl restart gunicorn.service
        sudo systemctl restart redis.service

  restart_services:
    runs-on: ubuntu-latest
    needs: install_project
    steps:
    - name: Restart gunicorn and redis
      run: |
        sudo systemctl restart gunicorn.service
        sudo systemctl restart redis.service
